# Generated by Django 5.1.7 on 2025-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupasfemininas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupasfemininas',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
