# Generated by Django 5.1.7 on 2025-05-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupasinfantis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField(null=True)),
            ],
        ),
    ]
