# Generated by Django 5.1.7 on 2025-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessorios',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
